class Leyenda {
  final String id;
  final String titulo;
  final String departamento;
  final String descripcionCorta;
  final String descripcionLarga;
  final String imagen;
  final String origen;
  final int nivelDeTerror;
  final String ritualDeProteccion;
  final String horaAparicion;
  final String habitat;
  final String? userId;

  Leyenda({
    required this.id,
    required this.titulo,
    required this.departamento,
    required this.descripcionCorta,
    required this.descripcionLarga,
    required this.imagen,
    required this.origen,
    this.nivelDeTerror = 3,
    this.ritualDeProteccion = 'No se conoce un ritual específico de protección. Mantente alerta.',
    this.horaAparicion = 'Durante la noche',
    this.habitat = 'Desconocido',
    this.userId,
  });
}
// Datos de ejemplo de leyendas bolivianas
final leyendasEjemplo = [
  Leyenda(
    id: '1',
    titulo: 'El Kari Kari',
    departamento: 'la_paz',
    descripcionCorta: 'El siniestro extractor de grasa humana del altiplano.',
    descripcionLarga:
        'En la profunda oscuridad y el frío penetrante del altiplano andino, camina una de las figuras más temidas de la cosmovisión aimara: el Kari Kari (o Kharisiri). A diferencia de otros monstruos o demonios, el Kari Kari es un ser humano vivo, generalmente un chamán o hechicero oscuro que ha hecho un pacto con fuerzas malignas para obtener sus poderes.\n\nEste oscuro personaje nunca ataca de frente ni por la fuerza. Su técnica consiste en acechar a los viajeros que caminan solos por las rutas desoladas o a personas que se quedan dormidas en autobuses o trenes. Utilizando campanas hipnóticas o polvos mágicos hechos de huesos humanos, induce a su víctima en un sueño profundo y antinatural.\n\nUna vez que la víctima está inconsciente, el Kari Kari realiza una incisión casi invisible en el abdomen y extrae la grasa humana, la cual utiliza posteriormente para rituales de magia negra, sacrificios, o incluso para vender a entidades oscuras. Al despertar, la persona no siente dolor inmediato, pero en los días siguientes desarrolla una fiebre letal y una debilidad extrema que ningún médico moderno puede diagnosticar. La única salvación es acudir de urgencia a un Yatiri (curandero tradicional) experto, antes de que sea demasiado tarde.',
    imagen: '🔪',
    origen: 'Tradición Aimara, Altiplano boliviano',
    nivelDeTerror: 5,
    ritualDeProteccion: 'Debes acudir de inmediato a un Yatiri (curandero tradicional) experto. Llevar un saquito con ajo, ruda y sal gruesa ayuda a repeler su presencia en caminos solitarios.',
    horaAparicion: 'Noches desoladas, medianoche',
    habitat: 'Senderos rurales y carreteras del Altiplano',
  ),
  Leyenda(
    id: '2',
    titulo: 'El Canto del Guajojó',
    departamento: 'santa_cruz',
    descripcionCorta: 'El lamento melancólico de una mujer convertida en ave.',
    descripcionLarga:
        'En lo más profundo de la selva oriental boliviana, se cuenta la trágica historia de la hija de un poderoso cacique de la tribu. La joven era dueña de una belleza inigualable y, contra todas las leyes de su pueblo, se enamoró perdidamente de un valiente guerrero perteneciente a una tribu enemiga.\n\nAmbos amantes se veían en secreto amparados por la oscuridad de la selva, hasta que un día el celoso cacique descubrió el romance. Ciego de ira, esperó al joven guerrero en el bosque y lo asesinó a sangre fría. Horas después, la muchacha fue al punto de encuentro y encontró el cuerpo inerte de su amado.\n\nEl dolor de la joven fue tan inmenso, y sus gritos de agonía tan desgarradores, que resonaron por toda la espesura atrayendo a un viejo chamán. El hechicero, conmovido por la intensidad de su sufrimiento y sabiendo que moriría de tristeza, decidió transformar a la muchacha en un ave nocturna. Desde esa noche, el Guajojó habita en las ramas de los árboles, emitiendo un canto lúgubre y escalofriante que suena como el llanto desconsolado de una mujer que busca eternamente a su amor perdido.',
    imagen: '🪶',
    origen: 'Mitología oriental boliviana',
    nivelDeTerror: 3,
    ritualDeProteccion: 'No debes imitar ni burlarte de su canto lúgubre, pues su sonido atrae la melancolía y la mala fortuna a quien ose interrumpir su dolor.',
    horaAparicion: 'Noches de luna llena',
    habitat: 'Copa de los árboles en la Selva Oriental',
  ),
  Leyenda(
    id: '3',
    titulo: 'El Tío de la Mina',
    departamento: 'potosi',
    descripcionCorta: 'El temido deidad y guardián de las profundidades.',
    descripcionLarga:
        'Bajo las imponentes faldas del legendario Cerro Rico de Potosí, se extiende un laberinto de túneles oscuros donde no llega la luz del sol ni la mirada de Dios. Allí, en las entrañas de la tierra, rige "El Tío", el dios del inframundo mineral. Es una deidad sincretizada entre el diablo católico y el Supay andino (dios del subsuelo).\n\nEn cada bocamina existe una estatua del Tío, moldeada en arcilla, con cuernos, un rostro aterrador, boca abierta y un falo erecto. Los mineros creen firmemente que "El Tío" es el verdadero dueño absoluto de toda la plata y el estaño de la montaña. Si él está contento, revela las vetas de mineral más puro; pero si se enfurece, provoca derrumbes, gases tóxicos y accidentes mortales.\n\nPara mantenerlo apaciguado, los mineros realizan el ritual de la "Challa" todos los viernes. Le ofrecen puñados de las mejores hojas de coca, cigarrillos encendidos que le colocan en la boca, y botellas de alcohol puro (singani). Nadie se atreve a trabajar sin antes pedir permiso al Tío, pues en la oscuridad de la mina, su ley es la única que importa.',
    imagen: '👹',
    origen: 'Sincretismo minero de Potosí',
    nivelDeTerror: 4,
    ritualDeProteccion: 'Realizar el ritual de la "Challa" cada viernes, dejándole hojas de coca frescas, un cigarrillo encendidos en su boca y vertiendo aguardiente a sus pies.',
    horaAparicion: 'Permanente (en el interior de la tierra)',
    habitat: 'Túneles y bocaminas profundas del Cerro Rico',
  ),
  Leyenda(
    id: '4',
    titulo: 'El Silbaco',
    departamento: 'beni',
    descripcionCorta: 'El silbido espectral que te pierde en la selva.',
    descripcionLarga:
        'En las noches cerradas de lluvia en la espesa Amazonía beniana, los lugareños y cazadores saben que no deben salir de sus campamentos. Existe un ente conocido como el Silbaco, el alma en pena de un hombre malvado que murió devorado por fieras salvajes o por castigo de la misma selva.\n\nEl Silbaco deambula invisible por entre la maleza. Su presencia se anuncia con un silbido prolongado, agudo y capaz de helar la sangre del hombre más valiente. La trampa mortal de esta entidad es jugar con la acústica y la mente: cuando su silbido se escucha claro, fuerte y cerca, significa que el ente está a kilómetros de distancia. Pero si el silbido se escucha muy suave, distante y ahogado...\n\nSignifica que el Silbaco está parado exactamente a tus espaldas, observándote. Quienes han cometido el error de intentar buscar el origen del sonido, terminan internándose profundamente en la selva, perdiendo por completo el sentido de la orientación, y nunca más se vuelve a saber de ellos.',
    imagen: '🌬️',
    origen: 'Tradición amazónica de Beni y Pando',
    nivelDeTerror: 4,
    ritualDeProteccion: 'Si escuchas su silbido muy suave, reza en silencio y no gires la cabeza bajo ningún concepto. Si respondes a su silbido o intentas seguirlo, te perderás para siempre.',
    horaAparicion: 'Noches cerradas de lluvia y tormenta',
    habitat: 'Espesura de la Amazonía beniana y pandina',
  ),
  Leyenda(
    id: '5',
    titulo: 'El Chiru Chiru',
    departamento: 'oruro',
    descripcionCorta: 'El ladrón justiciero devoto de la Virgen.',
    descripcionLarga:
        'A fines del siglo XVIII, la ciudad colonial de Oruro albergaba un personaje que parecía sacado de un cuento de justicieros: el Chiru Chiru. Su verdadero nombre, según algunos, era Nina Nina. Vestía harapos, tenía el cabello desordenado como el nido de un ave (de ahí el apodo "chiru chiru") y sobrevivía como un astuto ladrón.\n\nSin embargo, el Chiru Chiru no era un ratero ordinario. Operaba como un "Robin Hood" andino: robaba exclusivamente a los acaudalados mineros, corregidores y comerciantes ricos, para repartir todo el botín a escondidas entre los huérfanos, viudas y pobres de la ciudad. Además, tenía una devoción inquebrantable a la Virgen del Socavón, patrona de los mineros.\n\nUna noche, intentando asaltar la casa de un hombre adinerado, fue descubierto y apuñalado mortalmente. Arrastrándose malherido, logró llegar hasta el santuario del cerro Pie de Gallo. Días después, los mineros encontraron su cuerpo inerte y desangrado, pero con una expresión de total paz, tendido a los pies de la imagen de la Virgen de la Candelaria. Se dice que ella misma bajó para asistirlo en sus últimos momentos. Su historia encendió tal fervor que, en su honor y como promesa a la Virgen, nació el fastuoso Carnaval de Oruro.',
    imagen: '🗡️',
    origen: 'Historia colonial de Oruro',
    nivelDeTerror: 1,
    ritualDeProteccion: 'Llevar una medalla de la Virgen del Socavón y mostrar generosidad con los desfavorecidos. El Chiru Chiru es un alma protectora y no daña a los de buen corazón.',
    horaAparicion: 'Madrugadas frías y neblinosas',
    habitat: 'Minas coloniales y callejones antiguos de Oruro',
  ),
  Leyenda(
    id: '6',
    titulo: 'La Viuda Negra',
    departamento: 'cochabamba',
    descripcionCorta: 'La aparición seductora de venganza mortal.',
    descripcionLarga:
        'En los callejones oscuros y solitarios de los pueblos de Cochabamba, cuando la niebla desciende a altas horas de la noche, se manifiesta la Viuda. Es una mujer de silueta escultural y paso seductor, vestida completamente con ropas de luto antiguas, un espeso velo negro cubriendo su rostro, y que camina sollozando suavemente.\n\nLa Viuda suele aparecerse ante hombres trasnochadores, parranderos, esposos infieles o borrachos. Atraídos por la figura frágil de la mujer llorando y por su misterioso atractivo, los hombres intentan acercarse para consolarla o hacerle proposiciones indecentes. Ella nunca responde, simplemente camina rápidamente guiándolos hacia zonas periféricas, cementerios o barrancos.\n\nCuando finalmente el hombre logra alcanzarla y le quita el velo, la ilusión desaparece. El rostro de la mujer es una calavera descarnada con cuencas vacías que irradian un brillo rojo fuego, y suelta una carcajada demoníaca. El horror paraliza el corazón de sus víctimas: algunos mueren de un infarto fulminante en el lugar, otros caen por los barrancos, y los pocos sobrevivientes pierden la cordura para siempre.',
    imagen: '🕸️',
    origen: 'Leyenda urbana de los valles',
    nivelDeTerror: 5,
    ritualDeProteccion: 'Llevar consigo ruda macho o una pequeña botella de agua bendita. Si sientes que te sigue, muerde ruda y reza el Padre Nuestro sin mirar su rostro.',
    horaAparicion: 'Entre la medianoche y las 3:00 AM',
    habitat: 'Callejones oscuros, senderos con niebla y cementerios',
  ),
  Leyenda(
    id: '7',
    titulo: 'El Carretón de la Otra Vida',
    departamento: 'santa_cruz',
    descripcionCorta: 'Un carruaje fantasma hecho de huesos que cruza el llano.',
    descripcionLarga:
        'El llano cruceño es caluroso y pacífico, pero tiene un oscuro secreto que ronda las horas más silenciosas de la madrugada. A las tres de la mañana, un escalofriante chirrido de madera y huesos arrastrándose comienza a escucharse a lo lejos, acercándose inexorablemente a los pueblos: es el Carretón de la Otra Vida.\n\nEsta macabra aparición no está hecha de madera ordinaria. El armazón del carretón está construido con osamentas y fémures humanos, y las ruedas son cráneos gigantes que crujen contra la arena. Está tirado por enormes bueyes negros de ojos rojizos y transparentes, y conducido por un cochero encapuchado del cual solo se puede percibir una energía gélida.\n\nLa leyenda cuenta que este carretón es enviado desde el inframundo para recoger las almas de las personas que han muerto en pecado mortal y que se niegan a abandonar el mundo de los vivos. Quien por curiosidad asome la cabeza por la ventana para verlo pasar, corre el riesgo de ser subido a la fuerza al carretón, desapareciendo en la bruma sin dejar rastro alguno.',
    imagen: '💀',
    origen: 'Tradición popular camba',
    nivelDeTerror: 5,
    ritualDeProteccion: 'Si escuchas el chirrido a la distancia, entra de inmediato a tu casa, apaga las luces y evita mirar a través de las rendijas de las ventanas.',
    horaAparicion: 'A las 3:00 AM (la hora de las ánimas)',
    habitat: 'Caminos arenosos y calles desiertas de los pueblos cruceños',
  ),
  Leyenda(
    id: '8',
    titulo: 'El Duende de Tarija',
    departamento: 'tarija',
    descripcionCorta: 'Un ser travieso que enamora con su guitarra.',
    descripcionLarga:
        'A lo largo de los fértiles viñedos y quebradas de Tarija, se cuentan mil historias sobre el Duende. A diferencia de las figuras terroríficas de otros departamentos, el duende tarijeño tiene una personalidad más traviesa, pícara y romántica. Se describe como un niño o un enano que viste un enorme sombrero de paja de ala ancha y ropa de campesino tradicional.\n\nEl duende suele esconderse en árboles grandes, especialmente higueras, y lleva siempre consigo una pequeña guitarra o un charango con el cual toca melodías folclóricas asombrosamente bellas. Es inofensivo para los niños, a quienes a veces invita a jugar perdiéndolos temporalmente, pero su verdadera perdición son las muchachas jóvenes y hermosas.\n\nCuando se enamora de una joven, el duende se vuelve extremadamente celoso e insistente. Comienza a tirarle piedritas al techo por las noches, le esconde sus pertenencias y toca serenatas invisibles debajo de su ventana. Se dice que sus melodías tienen propiedades hipnóticas, y la única forma de ahuyentarlo para siempre es que la joven realice actos que al duende le resulten desagradables o sucios, ya que es un ser sumamente pulcro y remilgado.',
    imagen: '🎸',
    origen: 'Folclore de los valles de Tarija',
    nivelDeTerror: 2,
    ritualDeProteccion: 'El duende odia el desorden y las cosas sucias debido a su extrema pulcritud. Dejar ceniza o basura desordenada lo espantará rápidamente.',
    horaAparicion: 'Tardes calurosas de siesta y crepúsculo',
    habitat: 'Bajo las higueras, quebradas y viñedos de Tarija',
  ),
  Leyenda(
    id: '9',
    titulo: 'El Jichi',
    departamento: 'santa_cruz',
    descripcionCorta: 'El monstruoso guardián de las aguas dulces.',
    descripcionLarga:
        'En las vastas tierras del oriente boliviano, el agua dulce es el tesoro más preciado. Para proteger este recurso vital, la naturaleza misma creó al Jichi, un ser mitológico profundamente arraigado en la cosmovisión de los pueblos Chiquitanos, Guarayos y Moxeños.\n\nEl Jichi es una enorme bestia que combina rasgos de serpiente, saurio, sapo gigante y, a veces, un gran felino. Su cuerpo está cubierto de escamas brillantes que cambian de color según la hora del día. Su morada está en el fondo de las lagunas, curichis (pantanos) y ríos cristalinos. A pesar de su apariencia aterradora, no es un demonio, sino un protector estrictamente justo de la ecología.\n\nMientras los humanos respeten el entorno, no desperdicien el agua, y no pesquen o cacen en exceso, el Jichi mantendrá la fuente de agua pura e inagotable, incluso en tiempos de extrema sequía. Sin embargo, si los colonos contaminan el agua con químicos, usan dinamita para pescar, o matan por crueldad, el Jichi se ofende profundamente. El ser abandona su morada y, de la noche a la mañana, la gran laguna o el pozo se secan por completo, convirtiéndose en un árido arenal para siempre.',
    imagen: '🐍',
    origen: 'Mitología Chiquitana y Guaraní',
    nivelDeTerror: 3,
    ritualDeProteccion: 'Nunca ensucies ni desperdicies el agua de las lagunas. Ofrecer una muestra de respeto y mantener el entorno limpio asegura su favor eterno.',
    horaAparicion: 'Cualquier hora (permanece en las profundidades)',
    habitat: 'Lagunas, pantanos y ríos cristalinos del oriente',
  ),
  Leyenda(
    id: '10',
    titulo: 'El Manchay Puito',
    departamento: 'potosi',
    descripcionCorta: 'El romance trágico convertido en una melodía maldita.',
    descripcionLarga:
        'Esta es considerada una de las leyendas más tristes y oscuras de la colonia en la Villa Imperial de Potosí. Relata la historia de un clérigo sumamente respetado que, desafiando todos los votos de su orden, se enamoró apasionadamente de una joven y bella mujer. Juntos vivieron un romance clandestino pero intensamente feliz.\n\nEl destino intervino de forma cruel cuando el clérigo fue enviado a un viaje forzoso fuera de la ciudad. Durante su ausencia, la joven enfermó gravemente de una extraña fiebre y falleció en cuestión de días. Al regresar y enterarse, el sacerdote enloqueció de dolor. Incapaz de aceptar la separación, entró al cementerio en medio de una tormenta, desenterró el cadáver de su amada y llevó sus restos a su habitación.\n\nEn la cúspide de su locura, tomó la tibia de la mujer, le perforó unos agujeros y construyó una flauta rústica. Luego introdujo la flauta en un cántaro de barro con agua para darle resonancia. El instrumento fue llamado Manchay Puito (Infierno Temible). Se dice que las melodías que tocaba no sonaban a música, sino a los gritos de lamento desde el purgatorio, evocando tanta tristeza que quienes lo escuchaban desde la calle se quitaban la vida por depresión. El sacerdote murió de inanición tocando la flauta junto a los huesos de su amada.',
    imagen: '🏺',
    origen: 'Literatura y mito colonial potosino',
    nivelDeTerror: 4,
    ritualDeProteccion: 'Si escuchas su música fúnebre, tápate los oídos con cera o huye del lugar. Su sonido induce una melancolía que puede arrebatarte la voluntad.',
    horaAparicion: 'Noches de viento helado y tormenta',
    habitat: 'Casonas antiguas y catacumbas coloniales de Potosí',
  ),
  Leyenda(
    id: '11',
    titulo: 'La Casa de Gatos',
    departamento: 'sucre',
    descripcionCorta: 'Misterio felino en la ciudad blanca de Sucre.',
    descripcionLarga:
        'En los serpenteantes y empedrados callejones de la ciudad blanca de Sucre, muy cerca del centro histórico, se erigía una casona colonial que había estado abandonada desde las guerras de independencia. A simple vista, era solo un edificio en ruinas, pero los vecinos sabían que ocultaba un terrible secreto.\n\nLa casona estaba infestada por docenas de gatos negros, animales enormes, silenciosos, y todos con penetrantes ojos amarillos que parecían tener un brillo casi antinatural en la oscuridad. Estos felinos no maullaban ni pedían comida, simplemente se posaban en los muros y cornisas, vigilando cada movimiento en la calle como si fueran centinelas humanos.\n\nCuenta la leyenda que estos gatos eran en realidad un cónclave de brujas de la antigüedad que habían pactado con entidades oscuras para custodiar un monumental tesoro de oro español escondido en el aljibe de la casona. Varios aventureros y ladrones que intentaron saltar los muros para apoderarse del oro nunca volvieron a salir; solo se escuchaban maullidos ensordecedores a medianoche, seguidos de un silencio sepulcral.',
    imagen: '🐈‍⬛',
    origen: 'Leyenda colonial de Sucre',
    nivelDeTerror: 3,
    ritualDeProteccion: 'No intentes buscar tesoros en lugares malditos. Llevar consigo sal gruesa o un espejo de bolsillo sirve para repeler los hechizos de las brujas.',
    horaAparicion: 'Medianoche',
    habitat: 'Casonas abandonadas y tejados del centro de Sucre',
  ),
  Leyenda(
    id: '12',
    titulo: 'El Jukumari y la Doncella',
    departamento: 'la_paz',
    descripcionCorta: 'El rapto amoroso del mítico oso andino.',
    descripcionLarga:
        'El Jukumari, conocido en el mundo real como el oso de anteojos, posee un estatus legendario en las faldas de los Andes y la región de los Yungas. La narrativa oral le atribuye cualidades humanas: inteligencia, emociones complejas y debilidades terrenales.\n\nUna conocida leyenda relata que un Jukumari gigante, el rey de las montañas, espiaba diariamente a una hermosa y joven pastora que llevaba a sus llamas a pastar cerca del bosque nublado. Embelesado por su belleza y sus cantos, el oso esperó a que estuviera distraída, la cargó con delicadeza pero con fuerza imparable, y se la llevó a su cueva profunda y oculta en lo más alto de la montaña. Para evitar que escapara, cerró la entrada con una roca que solo él podía mover.\n\nContra toda expectativa, el oso no le hizo daño. Le traía frutas exóticas, miel silvestre y flores todos los días, tratándola como a una diosa. Con el pasar de los años, de esta unión prohibida entre la bestia y la humana nació un ser excepcional: un niño con rasgos de hombre pero cubierto de pelaje negro, poseedor de una fuerza colosal. Al final, este ser híbrido es quien lograría mover la roca, liberando a su madre para retornar a su pueblo y convirtiéndose en un héroe de fuerza legendaria.',
    imagen: '🐻',
    origen: 'Tradición aimara y quechua',
    nivelDeTerror: 3,
    ritualDeProteccion: 'Si te encuentras con un Jukumari, enciende una antorcha. Le temen al fuego y retrocederán ante la luz intensa.',
    horaAparicion: 'Durante el día y el atardecer',
    habitat: 'Bosques nublados de los Yungas y cuevas andinas',
  ),
  Leyenda(
    id: '13',
    titulo: 'La Leyenda del Chuchini',
    departamento: 'beni',
    descripcionCorta: 'Las colinas artificiales construidas por el tigre.',
    descripcionLarga:
        'A pocos kilómetros de la ciudad de Trinidad, en plena sabana de la Amazonía beniana, existen misteriosas elevaciones de tierra conocidas como las "Lomas de Chuchini". En idioma trinitario, Chuchini significa "Morada del Tigre" o "Cueva del Jaguar". Estas lomas son un rompecabezas ecológico que dio origen a fuertes supersticiones.\n\nLa arqueología moderna dice que fueron construidas hace miles de años por las grandes civilizaciones precolombinas de Moxos para evitar que sus aldeas desaparezcan en la época de inundaciones fluviales. Pero la leyenda indígena cuenta otra historia: afirman que fueron levantadas por una raza mítica y primigenia de seres mágicos mitad humanos y mitad jaguares.\n\nSegún la creencia, el Chuchini no solo es un refugio contra el agua, sino el custodio de inmensos tesoros dorados y sabidurías olvidadas enterradas en el lodo. Sin embargo, explorar sus túneles subterráneos acarrea una terrible maldición. Aquellos profanadores que se atreven a cavar buscando vasijas o metales preciosos despiertan a los grandes espíritus-jaguar que aún custodian la loma, causando infortunios irreparables, enfermedades inexplicables o la pérdida total de la razón.',
    imagen: '🐆',
    origen: 'Cultura Moxeña, Beni',
    nivelDeTerror: 4,
    ritualDeProteccion: 'No profanes las lomas sagradas ni intentes excavar en ellas. Si entras al territorio de Chuchini, pide permiso mentalmente a los espíritus-jaguar.',
    horaAparicion: 'Noches sin luna y de niebla amazónica',
    habitat: 'Lomas prehispánicas artificiales rodeadas de selva y pantano',
  ),
  Leyenda(
    id: '14',
    titulo: 'El Cóndor y la Cholita',
    departamento: 'la_paz',
    descripcionCorta: 'La doncella andina que aprendió a volar.',
    descripcionLarga:
        'El Mallku, el gran Cóndor de los Andes, es la deidad suprema de las alturas. Según una antigua y romántica leyenda, este majestuoso animal no siempre mantuvo forma de ave. Un día, surcando los cielos, observó a una joven cholita que pastoreaba su rebaño. Quedó tan fascinado por su gracia que decidió utilizar su magia.\n\nEl cóndor descendió tras unas rocas y se transformó en un apuesto y enigmático joven vestido de luto impecable: traje negro de bayeta, sombrero oscuro y una fina chalina blanca alrededor del cuello (emulando las plumas blancas de su cuello original). El apuesto forastero se acercó a la joven, la enamoró perdidamente con palabras dulces y, un día, le pidió que cerrara los ojos y la abrazó.\n\nAl abrirlos, la joven descubrió con terror y asombro que estaba volando por los cielos, atrapada en las garras del inmenso cóndor, directo hacia su nido en la montaña más alta e inaccesible. Aunque al principio lloró por sus padres y su rebaño, el cóndor le daba calor bajo sus alas y le traía la mejor carne fresca cocinada con el sol. Con el tiempo, a la joven le comenzaron a brotar plumas negras en los brazos, y eventualmente se convirtió ella misma en un cóndor, volando libre por la eternidad junto a su gran amor.',
    imagen: '🦅',
    origen: 'Mito andino de transformación',
    nivelDeTerror: 2,
    ritualDeProteccion: 'Llevar cascabeles o silbatos ruidosos al pastorear en zonas altas. El Mallku rehúye el alboroto y las multitudes.',
    horaAparicion: 'Al mediodía, cuando el sol está en su cénit',
    habitat: 'Cumbres escarpadas, precipicios y cunas cordilleranas',
  ),
  Leyenda(
    id: '15',
    titulo: 'El Mapinguari',
    departamento: 'pando',
    descripcionCorta: 'La bestia ciclópea de la espesura amazónica.',
    descripcionLarga:
        'En los bosques más cerrados, oscuros e impenetrables de la frontera entre Pando, Brasil y Perú, sobrevive el mito de una de las criaturas más temidas del folclore amazónico: el Mapinguari. Es descrito por los siringueros (extractores de goma) y castañeros como una verdadera monstruosidad de la naturaleza.\n\nSe dice que es un humanoide gigantesco, cubierto de un espeso pelaje rojizo que lo hace parecer un mono enorme o un oso perezoso prehistórico. Pero lo espeluznante de su anatomía es que solo tiene un gran ojo rojo en medio de la cabeza y una enorme y voraz boca vertical localizada en su abdomen, llena de colmillos afilados. Además, la criatura emite un olor tan fétido y pestilente que cualquiera que lo inhale queda inmovilizado por las náuseas y el terror.\n\nEl Mapinguari es extremadamente territorial y agresivo con los cazadores que destruyen la selva o matan animales por deporte. Los relatos cuentan que su piel endurecida, similar a la coraza de un caimán, lo hace completamente invulnerable a flechas y balas de escopeta. La única forma de matarlo, según los ancianos de las tribus locales, es dispararle un dardo envenenado exactamente en el centro del ombligo, su único punto débil.',
    imagen: '👁️',
    origen: 'Folclore amazónico fronterizo',
    nivelDeTerror: 5,
    ritualDeProteccion: 'El Mapinguari es invulnerable a las balas. Si te ataca, debes apuntar con una flecha o dardo con veneno de curare directamente a su ombligo.',
    horaAparicion: 'Noches oscuras de tormenta o calor extremo',
    habitat: 'Espesuras selváticas impenetrables de la Amazonía de Pando',
  ),
  Leyenda(
    id: '16',
    titulo: 'El Mojón con Cara',
    departamento: 'santa_cruz',
    descripcionCorta: 'El poste tallado testigo de un amor prohibido.',
    descripcionLarga:
        'En el Santa Cruz de la época colonial, cuando las calles eran de arena y la vida transcurría apaciblemente al ritmo del viento sur, vivía un joven carpintero de gran talento y alma sensible. El muchacho se enamoró profundamente de la hija de un orgulloso caballero español, quien consideraba al humilde artesano indigno de su linaje.\n\nLos amantes se veían en secreto por las noches a la luz de las velas. El joven solía esperar a su amada en una de las esquinas principales, apoyado en un grueso mojón de madera de cuchi que servía para evitar que las carretas golpearan la pared de la casa. En las largas horas de espera, el carpintero utilizó su cuchillo para tallar con esmero el mojón, dándole la forma de un rostro humano triste y contemplativo.\n\nUna noche, el padre de la joven descubrió el romance y ordenó a sus criados atacar al joven. A la mañana siguiente, el carpintero desapareció misteriosamente, pero en la esquina quedó el mojón tallado con un rostro perfecto, que parecía llorar en silencio bajo la lluvia. Los cruceños bautizaron la esquina como "El Mojón con Cara", recordándolo como un eterno monumento al amor sincero y prohibido.',
    imagen: '🪵',
    origen: 'Tradición cruceña colonial',
    nivelDeTerror: 1,
    ritualDeProteccion: 'Respetar las esquinas antiguas de la ciudad. Se dice que si tocas el mojón pensando en tu pareja, su amor durará para siempre.',
    horaAparicion: 'Noches templadas de viento sur',
    habitat: 'Calles empedradas e históricas del centro cruceño',
  ),
  Leyenda(
    id: '17',
    titulo: 'La Dama de Blanco de la Glorieta',
    departamento: 'sucre',
    descripcionCorta: 'La aparición aristocrática en el castillo de Sucre.',
    descripcionLarga:
        'En las afueras de la ciudad blanca de Sucre se erige el majestuoso Castillo de la Glorieta, una joya arquitectónica de finales del siglo XIX donde habitaron los únicos príncipes que tuvo Bolivia. Detrás de sus bellas torres de estilo mudéjar, bizantino y gótico, ronda la trágica presencia de una mujer vestida con un reluciente vestido de fiesta blanco de encaje francés.\n\nSe cuenta que es el alma en pena de una joven cortesana de la corte de los príncipes de la Glorieta, quien falleció repentinamente de amor tras ser separada de su amado por intrigas palaciegas. Desde entonces, su espíritu camina con gracia y melancolía por los jardines del castillo y los amplios salones de baile vacíos.\n\nLos vigilantes y visitantes nocturnos aseguran haber visto la silueta translúcida de la dama cruzando los puentes de piedra sobre el río Quirpinchaca y asomándose por las ventanas de la torre principal. La aparición no busca hacer daño, sino encontrar a su amante perdido; sin embargo, encontrarse con su mirada gélida provoca una intensa melancolía que puede durar días en el alma de quien la contempla.',
    imagen: '🏰',
    origen: 'Leyenda aristocrática de Sucre',
    nivelDeTerror: 2,
    ritualDeProteccion: 'Si te encuentras con la dama, no huyas corriendo ni le hables. Deja una rosa blanca en los jardines del castillo para que su alma encuentre descanso.',
    horaAparicion: 'Madrugadas neblinosas de invierno',
    habitat: 'Salones, pasillos y jardines del Castillo de la Glorieta',
  ),
  Leyenda(
    id: '18',
    titulo: 'El Tapado de Potosí',
    departamento: 'potosi',
    descripcionCorta: 'El misterioso caballero que oculta un tesoro colonial.',
    descripcionLarga:
        'Durante los años de gloria del Cerro Rico de Potosí, cuando la plata fluía por los callejones empinados, comenzó a aparecer un misterioso hombre vestido de gala colonial que siempre llevaba una capa oscura que cubría por completo su cuerpo y un sombrero de ala ancha que ocultaba su rostro. Nadie sabía su nombre ni su procedencia, pero todos lo llamaban "El Tapado".\n\nEl Tapado se aparecía en los callejones más oscuros, caminando silenciosamente. Se decía que era el guardián de una inmensa fortuna acumulada por avaros mineros españoles que murieron sin revelar la ubicación de sus entierros de plata. El alma del Tapado estaba condenada a vagar hasta encontrar a una persona generosa a quien entregarle el tesoro para poder descansar.\n\nQuienes se atrevieron a seguirlo cuentan que los guiaba hacia sótanos abandonados o catacumbas coloniales, donde desaparecía en un destello de luz, revelando vasijas llenas de monedas de plata pura. Sin embargo, si la persona mostraba codicia o maldad, el tesoro se convertía instantáneamente en carbón o cenizas, y el codicioso era arrojado con fuerza a la calle, perdiendo la cordura.',
    imagen: '🪙',
    origen: 'Leyendas de la Villa Imperial de Potosí',
    nivelDeTerror: 3,
    ritualDeProteccion: 'Mostrar humildad y caridad ante los caminantes nocturnos. Si eres guiado por el Tapado, debes prometer donar una parte del tesoro a los huérfanos.',
    horaAparicion: 'Noches de neblina espesa, medianoche',
    habitat: 'Callejones empinados y catacumbas de Potosí',
  ),
  Leyenda(
    id: '19',
    titulo: 'La Llorona de la Coronilla',
    departamento: 'cochabamba',
    descripcionCorta: 'El alma en pena que llora en la histórica colina.',
    descripcionLarga:
        'En la Colina de la Coronilla en Cochabamba, escenario de la heroica batalla de las heroínas por la independencia, los vecinos y transeúntes nocturnos reportan desde hace décadas el desgarrador lamento de una mujer. Se trata de La Llorona, un espíritu atormentado que busca incansablemente a sus hijos perdidos en las sombras.\n\nLa leyenda cuenta que fue una madre desesperada que, durante las violentas batallas de la independencia o en tiempos de peste colonial, perdió a sus hijos en medio del caos. Su dolor fue tan inmenso que su mente se quebró, y tras morir de tristeza, su alma quedó atada a la colina, vagando eternamente en el limbo de la noche.\n\nSu grito: "¡Ay mis hijos!", resuena con un eco metálico y fantasmal que eriza la piel. Los taxistas y caminantes que cruzan la base de la colina aseguran ver a una mujer alta, vestida de blanco o gris translúcido, flotando entre los árboles y desapareciendo cerca del monumento a las heroínas. Escuchar su lamento muy de cerca es presagio de mala suerte o enfermedad familiar.',
    imagen: '👵',
    origen: 'Tradición oral valluna',
    nivelDeTerror: 4,
    ritualDeProteccion: 'Llevar una pequeña cruz de madera o una medalla de la Virgen de Urkupiña. No respondas a sus lamentos ni intentes seguir su voz.',
    horaAparicion: 'Entre la medianoche y el amanecer',
    habitat: 'Colina de la Coronilla y senderos aledaños',
  ),
  Leyenda(
    id: '20',
    titulo: 'El Sajama y los Volcanes',
    departamento: 'oruro',
    descripcionCorta: 'La épica batalla de los gigantes de piedra.',
    descripcionLarga:
        'En los tiempos antiguos, cuando las montañas de los Andes eran gigantes vivientes y dioses de piedra, el imponente Mururata se alzaba orgulloso y desafiante, compitiendo en altura y majestuosidad con el gran Illimani. La soberbia del Mururata enfureció al creador del cosmos, quien en un acto de justicia divina, tomó una honda gigante y le rebanó la cima de un solo golpe, arrojándola hacia el altiplano.\n\nEsa cima decapitada voló cientos de kilómetros hasta posarse en las planicies de Oruro, convirtiéndose en el majestuoso e imponente nevado Sajama. Al verse solo en la estepa fría, el Sajama se coronó como el guardián absoluto de la llanura andina, protegiendo a los pueblos Uru de los fuertes vientos y de las tormentas heladas.\n\nLa mitología cuenta que el Sajama mantiene una conexión espiritual con otros volcanes de la región, como el Tata Sabaya y el volcán Tunupa. Cuando los volcanes rugen o muestran fumarolas, se cree que los espíritus de las montañas están comunicándose o recordando las batallas legendarias de la creación, protegiendo la tierra de cataclismos mayores a través de sus sacrificios.',
    imagen: '🏔️',
    origen: 'Cosmovisión Andina y Uru',
    nivelDeTerror: 1,
    ritualDeProteccion: 'Ofrecer una mesa ritual (K\'oa) al pie del nevado para pedir permiso antes de subir a su cima. El Sajama protege a los caminantes respetuosos.',
    horaAparicion: 'Durante el amanecer y atardecer',
    habitat: 'Cordillera Occidental y altiplano de Oruro',
  ),
  Leyenda(
    id: '21',
    titulo: 'La Llorona del Rincón de la Victoria',
    departamento: 'tarija',
    descripcionCorta: 'El espectro de agua de los valles tarijeños.',
    descripcionLarga:
        'El Rincón de la Victoria es uno de los parajes naturales más hermosos de Tarija, conocido por sus arroyos cristalinos, vegetación verde y cascadas refrescantes. Sin embargo, los lugareños saben que al caer el sol y cuando las sombras se adueñan de las cañadas, no se debe caminar solo cerca del cauce del agua.\n\nSe cuenta que el espectro de una mujer con el cabello mojado y ropajes largos de color celeste se manifiesta flotando sobre la superficie de las cascadas y pozas de agua. Es conocida como la Llorona del Agua. A diferencia del mito urbano tradicional, este ser es un espíritu de la naturaleza que lamenta la pérdida del equilibrio ecológico y llora por su trágico destino en los manantiales.\n\nLos lugareños advierten que su canto y sus sollozos tienen un magnetismo hipnótico. Si un caminante escucha su llanto, se sentirá irresistiblemente atraído a acercarse a la orilla de las pozas. En ese momento, la corriente puede volverse violenta de forma antinatural, arrastrando al curioso al fondo de las aguas profundas.',
    imagen: '💧',
    origen: 'Mitos de los valles tarijeños',
    nivelDeTerror: 3,
    ritualDeProteccion: 'No te acerques a las pozas profundas al anochecer. Si sientes que la corriente te llama, muerde una hoja de coca o lleva un amuleto de plata.',
    horaAparicion: 'Al caer el crepúsculo y noches húmedas',
    habitat: 'Cascadas, pozas y arroyos del Rincón de la Victoria',
  ),
  Leyenda(
    id: '22',
    titulo: 'La Yara (Madre del Agua)',
    departamento: 'pando',
    descripcionCorta: 'La hermosa y peligrosa sirena del río Acre.',
    descripcionLarga:
        'En los ríos calurosos y caudalosos del departamento de Pando, especialmente en el río Acre y el Madre de Dios, los navegantes y pescadores temen y respetan a la Yara (o Iara), conocida como la Madre del Agua. Se describe como una mujer de belleza extraordinaria, con cabellos negros larguísimos y una cola brillante de pez.\n\nLa Yara se posa sobre las rocas en medio de los ríos o en las orillas sombreadas por grandes árboles amazónicos durante las tardes calurosas. Su técnica de caza consiste en cantar melodías dulces, misteriosas y seductoras que viajan con el viento por la espesura. Cualquier pescador o navegante solitario que escuche su voz queda hipnotizado de inmediato.\n\nEl hombre hechizado guiará su canoa directamente hacia ella, arrojándose a las aguas profundas en un trance de amor. La Yara lo sumerge en su palacio submarino del cual nunca más regresará. Si un hombre logra sobrevivir al encuentro, perderá la cordura para siempre, suspirando de amor y mirando eternamente hacia los ríos, esperando que su amada vuelva por él.',
    imagen: '🧜‍♀️',
    origen: 'Mitología amazónica pandina',
    nivelDeTerror: 4,
    ritualDeProteccion: 'Taparse los oídos si se escuchan cantos extraños en el río por las tardes. Llevar ajo en la canoa ayuda a romper sus hechizos marinos.',
    horaAparicion: 'Tardes soleadas de siesta y noches de luna llena',
    habitat: 'Ríos Acre, Madre de Dios y lagunas de la selva pandina',
  ),
  Leyenda(
    id: '23',
    titulo: 'La Chola sin Cabeza',
    departamento: 'cochabamba',
    descripcionCorta: 'El espectro colonial que ronda los viejos callejones.',
    descripcionLarga:
        'En los laberintos de adobe y teja de la Cochabamba de antaño, cuando las farolas de vela apenas disipaban las tinieblas, comenzó a contarse la historia de una aparición aterradora: La Chola sin Cabeza. Se trata de la figura fantasmal de una mujer vestida con una pollera elegante y un mantón de Manila bordado, pero cuya cabeza ha desaparecido por completo.\n\nSegún la creencia popular, se trata del alma en pena de una mujer adinerada de la época colonial que cometió actos atroces contra sus sirvientes y sirvió a la hechicería oscura. Como castigo divino a sus pecados, fue decapitada en circunstancias misteriosas y su cuerpo arrojado a un pozo. Desde entonces, su espíritu camina con pasos lentos y rítmicos por las calles antiguas y empedradas.\n\nLos trasnochadores aseguran que el espectro suele aparecer flotando a unos centímetros del suelo. Al acercarse, se puede escuchar el roce de su pollera de seda y un murmullo lúgubre que emana del cuello cortado. Quienes intentan hablarle o tocarla caen desmayados de terror y despiertan al día siguiente con marcas moradas en la piel.',
    imagen: '👗',
    origen: 'Leyenda urbana colonial valluna',
    nivelDeTerror: 5,
    ritualDeProteccion: 'Si escuchas el roce de su pollera, arrodíllate, cierra los ojos y haz la señal de la cruz. El uso de agua bendita la aleja de inmediato.',
    horaAparicion: 'A las 12:00 AM (medianoche)',
    habitat: 'Callejones coloniales y casonas abandonadas de Cochabamba',
  ),
  Leyenda(
    id: '24',
    titulo: 'El Duende de Totora',
    departamento: 'cochabamba',
    descripcionCorta: 'El travieso habitante de los tejados coloniales.',
    descripcionLarga:
        'Totora es una de las joyas coloniales de Cochabamba, un pueblo de calles empedradas y tejados de arcilla roja que guardan el paso del tiempo. Entre sus rincones y chicherías tradicionales vive la leyenda de un duende sumamente juguetón y travieso, descrito como un niño pequeño con un enorme sombrero de ala ancha que le cubre la mitad del rostro.\n\nEl duende de Totora no tiene maldad, pero es sumamente insistente con sus travesuras. Le fascina trenzar los cabellos de las muchachas mientras duermen, esconder las llaves de las casas, tirar piedrecillas a las ventanas durante las tardes de siesta y agriar la chicha de maíz de las chicherías tradicionales si no se le deja una ofrenda.\n\nLos totoreños afirman que la presencia del duende se nota cuando se escucha un risita infantil y rítmica que proviene de las vigas del techo o de los huertos de durazno. Para ganarse su favor o mantenerlo tranquilo, los dueños de casa suelen dejar un pequeño plato con dulces o un vaso de chicha dulce en las esquinas de los patios coloniales.',
    imagen: '👒',
    origen: 'Tradición oral de Totora',
    nivelDeTerror: 2,
    ritualDeProteccion: 'Si te esconde las pertenencias, dile en voz alta y firme que te devuelva tu objeto mientras colocas tu calzado al revés en la entrada.',
    horaAparicion: 'Tardes calurosas de siesta, 3:00 PM',
    habitat: 'Tejados antiguos, patios coloniales y huertos de durazno',
  ),
  Leyenda(
    id: '25',
    titulo: 'El Huayra Tata',
    departamento: 'cochabamba',
    descripcionCorta: 'El ancestral y poderoso dios del viento del valle.',
    descripcionLarga:
        'En los fértiles valles cochabambinos, la agricultura y la vida dependen enteramente del clima. Para los antiguos pueblos que habitaban la región, el viento era regido por una deidad poderosa y respetada: el Huayra Tata (Padre Viento). Es un dios gigante que habita en las cumbres de las montañas y en los profundos abismos de la cordillera del Tunari.\n\nEl Huayra Tata controla las brisas suaves que traen la lluvia y polinizan los cultivos de maíz, pero también los huracanes devastadores y remolinos de polvo que azotan los campos secos. Se dice que cuando está enojado, baja de las alturas rugiendo con una fuerza descomunal, arrancando techos de paja y levantando densas nubes de tierra.\n\nLos agricultores tradicionales aún le rinden tributo soplando hojas de coca en dirección a los cuatro puntos cardinales al iniciar la siembra. Creer en el Huayra Tata es parte de la conexión profunda con la Pachamama y las fuerzas de la naturaleza, recordando que la tierra debe ser tratada con respeto y devoción.',
    imagen: '🌬️',
    origen: 'Mitología quechua y precolombina',
    nivelDeTerror: 3,
    ritualDeProteccion: 'Ofrecer hojas de coca y un chorro de chicha de maíz a la Pachamama cuando el viento empiece a soplar con violencia inusual.',
    horaAparicion: 'Durante el crepúsculo y tormentas de agosto',
    habitat: 'Cumbres de la Cordillera del Tunari y cielos de los valles',
  ),
  Leyenda(
    id: '26',
    titulo: 'La Dama de la Línea',
    departamento: 'cochabamba',
    descripcionCorta: 'El fantasma que advierte a los viajeros del tren.',
    descripcionLarga:
        'Durante la época dorada del ferrocarril en Bolivia, Cochabamba estaba conectada por una red de vías metálicas que cruzaban el valle. En una de las curvas más pronunciadas y peligrosas de la antigua vía del tren, comenzó a aparecer la silueta de una mujer vestida con un traje de época oscuro que se paraba en medio de los rieles a altas horas de la noche.\n\nSe cuenta que es el alma de una joven que falleció trágicamente arrollada por la locomotora mientras esperaba a su esposo que regresaba del mineral. Desde su muerte, su espectro vaga por los rieles con una linterna o un farol de mano parpadeante, advirtiendo a los maquinistas y caminantes sobre la proximidad de un peligro en la vía.\n\nLos antiguos maquinistas aseguraban que al ver el farol rojo en la distancia, frenaban el tren de emergencia, descubriendo segundos después que la vía estaba bloqueada por derrumbes de rocas o troncos caídos. Al intentar buscar a la mujer para agradecerle, el farol se apagaba y la dama desaparecía en la neblina nocturna.',
    imagen: '🚂',
    origen: 'Leyendas ferroviarias cochabambinas',
    nivelDeTerror: 3,
    ritualDeProteccion: 'Llevar siempre una linterna encendida y evitar caminar por las vías abandonadas en las noches de neblina espesa.',
    horaAparicion: 'Noches neblinosas de invierno, 2:00 AM',
    habitat: 'Líneas ferroviarias antiguas y túneles de tren del valle',
  ),
  Leyenda(
    id: '27',
    titulo: 'Incallajta y el Tesoro del Inca',
    departamento: 'cochabamba',
    descripcionCorta: 'El tesoro imperial protegido por espíritus incaicos.',
    descripcionLarga:
        'Incallajta es el complejo arqueológico incaico más grande e imponente de Cochabamba, construido por el emperador Tupac Yupanqui como fortaleza militar y santuario. La leyenda cuenta que tras la caída del imperio y la captura de Atahualpa, los generales incas escondieron una inmensa cantidad de oro y objetos sagrados en los cimientos y pasadizos subterráneos de la fortaleza.\n\nEste tesoro imperial está custodiado por los espíritus de los guerreros incas que juraron proteger la riqueza de la codicia de los conquistadores españoles. Se dice que quienes visitan las ruinas con intenciones de buscar metales preciosos o profanar el lugar sagrado caen bajo una terrible maldición.\n\nLos comunarios de la zona reportan que en las noches despejadas se pueden escuchar cantos fúnebres andinos y el retumbar de tambores imperiales que provienen de las ruinas. Se han visto luces extrañas (antorchas espectrales) recorriendo la gran muralla de piedra del templo, advirtiendo que el tesoro sagrado nunca debe ser retirado de su morada eterna.',
    imagen: '🪙',
    origen: 'Mitos del imperio Incaico en Cochabamba',
    nivelDeTerror: 4,
    ritualDeProteccion: 'Entrar a las ruinas con respeto, dejando una ofrenda de coca o una piedra en la apacheta de ingreso para pedir la bendición de los ancestros.',
    horaAparicion: 'Noches de luna llena y solsticio de invierno',
    habitat: 'Ruinas de la Fortaleza de Incallajta, Pocona',
  ),
];
