// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    if (Platform.isMacOS) {
      return macos;
    }
    if (Platform.isWindows) {
      return windows;
    }
    if (Platform.isLinux) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbNyCVLKQumTO0CvuJ_aUXX2I9K1pnGs',
    appId: '1:906313688113:android:c6913e27b604cb70c0e110',
    messagingSenderId: '906313688113',
    projectId: 'leyendas-app',
    storageBucket: 'leyendas-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPbNyCVLKQumTO0CvuJ_aUXX2I9K1pnGs',
    appId: '1:906313688113:ios:abcdefghijklmnopqrst',
    messagingSenderId: '906313688113',
    projectId: 'leyendas-app',
    storageBucket: 'leyendas-app.firebasestorage.app',
    iosBundleId: 'com.purplemist.appLeyendas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPbNyCVLKQumTO0CvuJ_aUXX2I9K1pnGs',
    appId: '1:906313688113:macos:abcdefghijklmnopqrst',
    messagingSenderId: '906313688113',
    projectId: 'leyendas-app',
    storageBucket: 'leyendas-app.firebasestorage.app',
    iosBundleId: 'com.purplemist.appLeyendas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPbNyCVLKQumTO0CvuJ_aUXX2I9K1pnGs',
    appId: '1:906313688113:windows:abcdefghijklmnopqrst',
    messagingSenderId: '906313688113',
    projectId: 'leyendas-app',
    storageBucket: 'leyendas-app.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDPbNyCVLKQumTO0CvuJ_aUXX2I9K1pnGs',
    appId: '1:906313688113:linux:abcdefghijklmnopqrst',
    messagingSenderId: '906313688113',
    projectId: 'leyendas-app',
    storageBucket: 'leyendas-app.firebasestorage.app',
  );
}
